# Generated by Django 4.0.6 on 2023-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('token', models.CharField(max_length=100)),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField()),
                ('minsActive', models.IntegerField()),
                ('minsInactive', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
