# Generated by Django 4.0.6 on 2023-03-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_attendance_is_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('loginTime', models.DateTimeField()),
                ('ModifiedOn', models.DateTimeField()),
            ],
        ),
    ]
