# Generated by Django 4.0.6 on 2023-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamps',
            old_name='ModifiedOn',
            new_name='modifiedOn',
        ),
        migrations.AlterField(
            model_name='timestamps',
            name='emp_id',
            field=models.CharField(max_length=100),
        ),
    ]
