# Generated by Django 4.0.6 on 2023-03-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_modifiedon_timestamps_modifiedon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='state',
            field=models.CharField(default='is_connected', max_length=100),
            preserve_default=False,
        ),
    ]
