# Generated by Django 4.0.6 on 2023-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_timestamps_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='minsActive',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='minsInactive',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestamps',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
