# Generated by Django 4.0.6 on 2023-04-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamps',
            name='temp',
        ),
    ]
